import { Project } from "@/types";
import { TechnologyType } from "@/types/enums";

export const PROJECTS: Project[] = [
  {
    id: "1",
    title: "StudyMate",
    description: "Connects learners across the world — helping you find your ideal study partner, collaborate, and grow faster together.",
    content: "StudyMate is a platform designed to help students find study partners, collaborate on projects, and share resources. The platform features real-time messaging, study group creation, and a resource library.",
    images: [
      "https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=modern%20education%20platform%20interface%20with%20students%20collaborating%2C%20clean%20UI%2C%20responsive%20design&image_size=square_hd",
    ],
    features: [
      "Find study partners worldwide",
      "Real-time messaging",
      "Study group creation",
      "Resource library",
    ],
    liveUrl: "https://studymateass.netlify.app/",
    backendUrl: "https://github.com/souravhalder-dev/StudyMate-Server",
    frontendUrl: "https://github.com/souravhalder-dev/StudyMate-Client",
    views: 0,
    isDeleted: false,
    deletedAt: null,
    createdAt: new Date(),
    updatedAt: new Date(),
    technologies: [
      {
        id: "t1",
        projectId: "1",
        technologyId: "tech1",
        isDeleted: false,
        deletedAt: null,
        createdAt: new Date(),
        updatedAt: new Date(),
        technology: {
          id: "tech1",
          name: "React 19",
          type: TechnologyType.FRONTEND,
          icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/react/react-original.svg",
          isDeleted: false,
          deletedAt: null,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      },
      {
        id: "t2",
        projectId: "1",
        technologyId: "tech2",
        isDeleted: false,
        deletedAt: null,
        createdAt: new Date(),
        updatedAt: new Date(),
        technology: {
          id: "tech2",
          name: "Tailwind CSS 4",
          type: TechnologyType.FRONTEND,
          icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/tailwindcss/tailwindcss-original.svg",
          isDeleted: false,
          deletedAt: null,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      },
      {
        id: "t3",
        projectId: "1",
        technologyId: "tech3",
        isDeleted: false,
        deletedAt: null,
        createdAt: new Date(),
        updatedAt: new Date(),
        technology: {
          id: "tech3",
          name: "Framer Motion",
          type: TechnologyType.FRONTEND,
          icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/react/react-original.svg",
          isDeleted: false,
          deletedAt: null,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      },
      {
        id: "t4",
        projectId: "1",
        technologyId: "tech4",
        isDeleted: false,
        deletedAt: null,
        createdAt: new Date(),
        updatedAt: new Date(),
        technology: {
          id: "tech4",
          name: "React Router v7",
          type: TechnologyType.FRONTEND,
          icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/react/react-original.svg",
          isDeleted: false,
          deletedAt: null,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      },
      {
        id: "t5",
        projectId: "1",
        technologyId: "tech5",
        isDeleted: false,
        deletedAt: null,
        createdAt: new Date(),
        updatedAt: new Date(),
        technology: {
          id: "tech5",
          name: "Axios",
          type: TechnologyType.TOOL,
          icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/javascript/javascript-original.svg",
          isDeleted: false,
          deletedAt: null,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      },
      {
        id: "t6",
        projectId: "1",
        technologyId: "tech6",
        isDeleted: false,
        deletedAt: null,
        createdAt: new Date(),
        updatedAt: new Date(),
        technology: {
          id: "tech6",
          name: "Firebase",
          type: TechnologyType.BACKEND,
          icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/firebase/firebase-plain.svg",
          isDeleted: false,
          deletedAt: null,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      },
    ],
    challenges: [
      "Implementing real-time messaging with Firebase",
      "Ensuring smooth user experience across different devices",
      "Managing user authentication securely",
    ],
    futurePlans: [
      "Add video conferencing for study sessions",
      "Implement a quiz feature for self-assessment",
      "Add AI-powered study recommendations",
    ],
  },
  {
    id: "2",
    title: "Portfolio Website",
    description: "A modern, responsive portfolio website showcasing projects and skills with smooth animations.",
    content: "This portfolio website is built with Next.js and Tailwind CSS, featuring a clean design, dark/light mode, and smooth scroll animations.",
    images: [
      "https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=modern%20developer%20portfolio%20website%20with%20clean%20design%2C%20dark%20mode%2C%20project%20cards&image_size=square_hd",
    ],
    features: [
      "Dark/Light mode toggle",
      "Smooth scroll animations",
      "Responsive design",
      "Project showcase",
    ],
    liveUrl: "https://example.com",
    backendUrl: "https://github.com/souravhalder-dev/portfolio-server",
    frontendUrl: "https://github.com/souravhalder-dev/portfolio",
    views: 0,
    isDeleted: false,
    deletedAt: null,
    createdAt: new Date(),
    updatedAt: new Date(),
    technologies: [
      {
        id: "t7",
        projectId: "2",
        technologyId: "tech7",
        isDeleted: false,
        deletedAt: null,
        createdAt: new Date(),
        updatedAt: new Date(),
        technology: {
          id: "tech7",
          name: "Next.js",
          type: TechnologyType.FRONTEND,
          icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nextjs/nextjs-original.svg",
          isDeleted: false,
          deletedAt: null,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      },
      {
        id: "t8",
        projectId: "2",
        technologyId: "tech8",
        isDeleted: false,
        deletedAt: null,
        createdAt: new Date(),
        updatedAt: new Date(),
        technology: {
          id: "tech8",
          name: "Tailwind CSS",
          type: TechnologyType.FRONTEND,
          icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/tailwindcss/tailwindcss-original.svg",
          isDeleted: false,
          deletedAt: null,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      },
      {
        id: "t9",
        projectId: "2",
        technologyId: "tech9",
        isDeleted: false,
        deletedAt: null,
        createdAt: new Date(),
        updatedAt: new Date(),
        technology: {
          id: "tech9",
          name: "TypeScript",
          type: TechnologyType.LANGUAGE,
          icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/typescript/typescript-original.svg",
          isDeleted: false,
          deletedAt: null,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      },
    ],
    challenges: [
      "Implementing smooth animations without affecting performance",
      "Ensuring accessibility across all components",
      "Creating a responsive design for all screen sizes",
    ],
    futurePlans: [
      "Add a blog section",
      "Implement a contact form with email integration",
      "Add more interactive elements",
    ],
  },
  {
    id: "3",
    title: "Task Manager Pro",
    description: "A powerful task management application with drag-and-drop functionality and team collaboration features.",
    content: "Task Manager Pro helps teams organize work, track progress, and collaborate efficiently with features like kanban boards, task assignments, and deadlines.",
    images: [
      "https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=task%20management%20app%20with%20kanban%20board%2C%20drag%20and%20drop%2C%20team%20collaboration&image_size=square_hd",
    ],
    features: [
      "Kanban board view",
      "Drag-and-drop functionality",
      "Team collaboration",
      "Task assignments and deadlines",
    ],
    liveUrl: "https://example-task-manager.com",
    backendUrl: "https://github.com/souravhalder-dev/task-manager-server",
    frontendUrl: "https://github.com/souravhalder-dev/task-manager-client",
    views: 0,
    isDeleted: false,
    deletedAt: null,
    createdAt: new Date(),
    updatedAt: new Date(),
    technologies: [
      {
        id: "t10",
        projectId: "3",
        technologyId: "tech10",
        isDeleted: false,
        deletedAt: null,
        createdAt: new Date(),
        updatedAt: new Date(),
        technology: {
          id: "tech10",
          name: "React",
          type: TechnologyType.FRONTEND,
          icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/react/react-original.svg",
          isDeleted: false,
          deletedAt: null,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      },
      {
        id: "t11",
        projectId: "3",
        technologyId: "tech11",
        isDeleted: false,
        deletedAt: null,
        createdAt: new Date(),
        updatedAt: new Date(),
        technology: {
          id: "tech11",
          name: "Node.js",
          type: TechnologyType.BACKEND,
          icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nodejs/nodejs-original.svg",
          isDeleted: false,
          deletedAt: null,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      },
      {
        id: "t12",
        projectId: "3",
        technologyId: "tech12",
        isDeleted: false,
        deletedAt: null,
        createdAt: new Date(),
        updatedAt: new Date(),
        technology: {
          id: "tech12",
          name: "MongoDB",
          type: TechnologyType.DATABASE,
          icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/mongodb/mongodb-original.svg",
          isDeleted: false,
          deletedAt: null,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      },
    ],
    challenges: [
      "Implementing drag-and-drop with smooth animations",
      "Managing real-time updates for team collaboration",
      "Ensuring data consistency across devices",
    ],
    futurePlans: [
      "Add time tracking for tasks",
      "Implement integration with calendar apps",
      "Add analytics and reporting features",
    ],
  },
];
